### ISSUE TITLE
启动时闪退

### ISSUE THREAD

**Issue by yongyecc** [yongyecc/apksheller#5]
```
--------- beginning of crash
04-18 12:23:11.167 24144 24144 E AndroidRuntime: FATAL EXCEPTION: main
04-18 12:23:11.167 24144 24144 E AndroidRuntime: Process: game.vewf48s4d8f48ef68th9hr.cf5d8g48e8r6g9rw, PID: 24144
04-18 12:23:11.167 24144 24144 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.DexClassLoader[DexPathList[[zip file "/data/user/0/game.vewf48s4d8f48ef68th9hr.cf5d8g48e8r6g9rw/cache/yongye"],nativeLibraryDirectories=[/data/user/0/game.vewf48s4d8f48ef68th9hr.cf5d8g48e8r6g9rw/lib, /system/lib64, /product/lib64]]] couldn't find "libmain.so"
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1083)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at com.unity3d.player.UnityPlayer.<clinit>(Unknown Source:10)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at com.unity3d.player.UnityPlayerActivity.onCreate(Unknown Source:28)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at game.vewf48s4d8f48ef68th9hr.cf5d8g48e8r6g9rw.MainActivity.onCreate(MainActivity.java:34)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-18 12:23:11.167 24144 24144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by yongyecc** [comment]
原因：classloader的so目录设置有问题
